version: 0.2

phases:
  install:
    runtime-versions:
      kubectl: 1.29
    commands:
      - echo Installing dependencies...
      - curl -o aws-iam-authenticator https://amazon-eks.s3.eu-central-1.amazonaws.com/1.29.0/2023-11-10/bin/linux/amd64/aws-iam-authenticator
      - chmod +x ./aws-iam-authenticator
      - mv aws-iam-authenticator /usr/local/bin/
  pre_build:
    commands:
      - echo Logging in to Amazon EKS...
      - aws eks update-kubeconfig --name pet-tracker-eks --region eu-central-1
  build:
    commands:
      - echo Applying Kubernetes manifests...
      - kubectl apply -f k8s/
artifacts:
  files:
    - '**/*'