version: 0.2

phases:
  install:
    runtime-versions:
      kubectl: 1.29
    commands:
      - echo "Verifying kubectl file..."
      - ls -l /tmp/cp-action-source/dist/kubectl/kubectl
      - if [ -d /tmp/cp-action-source/dist/kubectl/kubectl ]; then echo "It's a directory!"; else echo "It's a file!"; fi
      - curl -LO https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - sudo mv ./kubectl /usr/local/bin/kubectl
  pre_build:
    commands:
      - echo Logging in to Amazon EKS...
      - aws eks update-kubeconfig --name pet-tracker-eks --region eu-central-1
  build:
    commands:
      - echo Applying Kubernetes manifests...
      - kubectl apply -f k8s/*.yaml
artifacts:
  files:
    - '**/*'