name: Deploy to EKS

on:
  push:
    branches:
      - main
    paths:
      - 'k8s/**'

env:
  AWS_REGION: eu-central-1
  EKS_CLUSTER_NAME: pet-tracker-eks

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f k8s/frontend/
          kubectl apply -f k8s/backend/
          kubectl apply -f k8s/ingress.yaml